# -*- coding: utf-8 -*-
"""Rest Service (Flask).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAiFFa4gsbCK952Qe1uzWjmS-FYTGwHO
"""

# Instalando

!pip install flask flask-ngrok

# Criando o server
import json


from flask_ngrok import run_with_ngrok
from flask import Flask, request, make_response


app = Flask(__name__)

run_with_ngrok(app)   #starts ngrok when the app is run
@app.route("/", methods = ['GET', 'POST', 'DELETE'])
def home():

    pessoas = [{"nome": "Bruno Rocha"},
               {"nome": "Arjen Lucassen"},
               {"nome": "Anneke van Giersbergen"},
               {"nome": "Steven Wilson"}]
    response = make_response(json.dumps(pessoas))
    response.content_type = "application/json"

    return response

    #return "<h1>Running Flask on Google Colab!</h1>"

app.run()

