# -*- coding: utf-8 -*-
"""Curso Python Huawei (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1If8Uisj7WUn-2-_84ZPOVlNdfpVuToqA

# Módulo Intermediário

## 10.4
"""

UF = {}
print('Leitura dos dados')

while True:
  sigla = input('\nDigite a sigla: ')

  if sigla == '':
    break
  elif sigla in UF:
    print(f'  A sigla {sigla} já está cadastrada!')
    continue

  estado = input('Digite o nome do estado: ')
  capital = input('Digite o nome da capital: ')
  pib = float(input('Digite o valor do PIB do estado: '))
  dictItem = {'nome': estado, 'capital': capital, 'pib': pib} # add dicionário aninhado
  UF[sigla] = (estado, capital, pib)

print('\n   {:15} {:15} {:>10}'.format('Estado', 'Capital', 'PIB (R$ bi)'))

for sigla, dados in UF.items():
  print('({}) {:15} {:15} {:10.2f}'.format(sigla, dados['nome'], dados['capital'], dados['pib']))

"""## 11.1"""

arq = open('saida_er_11.1.txt', 'w')
A = int(input('Digite um inteiro: '))

while A != 0:
  arq.write(f'{A}\n')
  A = int(input('Digite um inteiro: '))

arq.close()
print('\nFim do Programa!')

"""## 11.3"""

Lst = []
X = float(input('Digite um número real: '))

while X != 0:
  Lst.append(f'{X:.3f}\n')
  X = float(input('Digite um número real: '))

arq = open('saida_er_11.3.txt', 'w')
arq.writelines(Lst)
arq.close()
print('Fim do Programa!')

"""## 11.4"""

Lst = []
arqEnt = open('entrada_er_11.4.txt', 'r')
linha = arqEnt.readline()

while linha != '':
  Lst.append(int(linha))
  linha = arqEnt.readline()

arqEnt.close()
print('Lista lida do arquivo')
print(Lst)
soma = sum(Lst)
print(f'Soma dos valores: {soma}')
qtde = len(Lst)
print(f'Quantidade de valores: {qtde}')
print(f'Média dos valores: {soma/qtde}')
minimo = min(Lst)
print(f'Menor valor: {minimo}')
maximo = max(Lst)
print(f'Maior valor: {maximo}')
print('\nFim do Programa!')

"""## 11.5"""

Lst = []
arqEnt = open('entrada_er_11.4.txt', 'r')

for linha in arqEnt:
  Lst.append(int(linha))

print('Lista lida do arquivo')
print(Lst)
soma = sum(Lst)
print(f'Soma dos valores: {soma}')
qtde = len(Lst)
print(f'Quantidade de valores: {qtde}')
print(f'Média dos valores: {soma/qtde}')
minimo = min(Lst)
print(f'Menor valor: {minimo}')
maximo = max(Lst)
print(f'Maior valor: {maximo}')
print('\nFim do Programa!')

"""## 11.6"""

estoque = {}
print('Estoque: \n')

for linha in open('/entrada_er_11.6.txt', 'r'):
  lst = linha.rstrip().split(';')
  print(lst)
  cod = int(lst[0])
  qtde = int(lst[1])
  pcunit = float(lst[2])
  estoque[cod] = (qtde, pcunit)

print('\nValores Carregados no Dicionário: \n')
print(estoque)
print('\nExibição dos Dados na Forma de Tabela: \n')
total_geral = 0

for cod, dados in estoque.items():
  tot = dados[0] * dados[1]
  total_geral += tot
  print(f'  {cod}: {dados[0]: 5d} x {dados[1]: 6.2f} = {tot: 8.2f}')

print(' ' * 24, f'{total_geral: 8.2f}')

"""## 11.7"""

cod_gravacao = input('Digite a codificação de gravação: ')
cod_leitura = input('Digite a codificação de leitura: ')
print('\nEtapa de gravação do arquivo')
arq = open('codificação.txt', 'w', encoding = cod_gravacao if cod_gravacao.upper() != 'ANSI' else 'cp1252')
arq.write('Gravação de arquivo\n')
arq.write('Acentos: á, é, í, Á, É, Í, ç, Ç\n')
arq.close()
print('\nEtapa de leitura do arquivo')
arq = open('codificação.txt', 'r', encoding = cod_leitura if cod_leitura.upper() != 'ANSI' else 'cp1252')
s = arq.readline()
print(s.rstrip())
s = arq.readline()
print(s.rstrip())
arq.close()

def func(l, i):
    if i + 1 < len(l):
        return func(l, i + 1)
    else:
        return l[i]

func([ 1, 2, 3, 4, 5], 2)

x = int(input('Digite um número inteiro: '))
[x - 2 if x > 2 else x + 3]