# -*- coding: utf-8 -*-
"""GeeksForGeeks Examples And Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQKzQ3dhk8RL0gl48koZ2wzulkrJe2Ug


"""# Array Leaders"""

def leaders(arr):
  res = []
  max_from_right = -1

  for i in range(len(arr) - 1, -1, -1):
    if arr[i] >= max_from_right:
      res.append(arr[i])
      max_from_right = arr[i]

  res.reverse()
  print(res)

leaders([16, 17, 4, 3, 5, 2])

"""# Array Duplicates"""

arr = [1, 2, 3, 1, 3, 6, 6]
arr.sort()
res = sorted(arr)
print(arr)
print(res)

"""# Binary Search"""

def binary_search(arr, k):
  for i in range(len(arr)):
    if arr[i] == k:
      return i
  return -1

binary_search([1, 2, 3, 4, 5], 4)

"""# Missing And Repeating"""

def findTwoElement(arr):
  n = len(arr)
  arr.sort()
  res = []

  for i in range(n - 1):
    if arr[i] == arr[i + 1]:
      res.append(arr[i])

  for i in range(1, n):
    if i not in arr:
      res.append(i)
      break

  return res

findTwoElement([4, 3, 6, 2, 1, 1, 4, 7, 12])

"""# Floor In A Sorted Array"""

def findFloor(arr, x):
    low = 0
    high = len(arr) - 1
    i_floor = -1

    while (low <= high):
        mid = (low + high) // 2

        if arr[mid] <= x:
            i_floor = mid
            low = mid + 1
        else:
            high = mid - 1

    return i_floor

findFloor([1, 2, 8, 10, 10, 12, 19], 11)

"""# Count Digits"""

def evenlyDivides(n):
  s = str(n)
  digits = []

  for char in s:
    digit = int(char)
    digits.append(digit)

  q = 0

  for digit in digits:
    if digit != 0 and n % digit == 0:
      q += 1

  return q

evenlyDivides(2446)

"""# Two Sum Pairs With 0 Sum"""

def getPairs(arr):
        pairs = set()
        for i in range(len(arr)):
            for j in range(i + 1, len(arr)):
                if arr[i] + arr[j] == 0:
                    if arr[i] < arr[j]:
                      pairs.add((arr[i], arr[j]))
                    else:
                      pairs.add((arr[j], arr[i]))
                else:
                  continue
        return sorted(list(pairs))

getPairs([6, 1, 8, 0, 4, -8, -9, -1, -10, -6, -5])

"""# FizzBuzz"""

number = int(input("Digite um número inteiro: "))

if(number % 3 == 0 and number % 5 == 0): print("\nNúmero FizzBuzz: " + str(number))
elif(number % 3 == 0): print("\nNúmero Fizz: " + str(number))
elif(number % 5 == 0): print("\nNúmero Buzz: " + str(number))
else:
  print("\Número nem Fizz nem Buzz: " + str(number))

"""# Greatest of Three"""

a = int(input("Digite o primeiro número: "))
b = int(input("\nDigite o segundo número: "))
c = int(input("\nDigite o terceiro número: "))

def find_greatest_number(a, b, c):
    return max(a, b, c)

print("\nO maior destes três números é: " + str(find_greatest_number(a, b, c)))

"""# Average"""

arr = [int(x) for x in input("Digite os números separados por espaço: ").split()]
size = 0
sum = 0

for i in arr:
  if i >= 0:
    size += 1
    sum += i
    avg = sum / size

print("\nO valor médio destes números é: " + str(float(avg)))

"""# Tuple 1"""

list1 = [int(i) for i in input("Digite os números separados por espaço: ").split()]
tuple1 = tuple(i * 2 for i in list1)

print("\nLista: " + str(list1))
print("\nA tupla de Lista com o valor dos elementos dobrados é: " + str(tuple1))

"""# Length of The List"""

list1 = [int(i) for i in input("Digite os números separados por espaço: ").split()]

print("\nLista: " + str(list1))
print("\nO comprimento de Lista é: " + str(len(list1)))

"""# Sum The List"""

list1 = [int(i) for i in input("Digite os números separados por vírgula: ").split(",")]

print("\nLista: " + str(list1))
print("\nA soma dos elementos de Lista é: " + str(sum(list1)))

"""# Decrement List Values

"""

arr = [int(i) for i in input("Digite os números separados por vírgula: ").split(",")]

print("\nLista: " + str(arr))
i = 0

while i < len(arr):
  arr[i] = arr[i] - 1
  i += 1

print("\nEsta Lista com seus elementos decrementados é: " + str(arr))

"""# List Traversal Reverse

"""

arr = [int(i) for i in input("Digite os números separados por vírgula: ").split(",")]

print("\nLista: " + str(arr))

arr.reverse()

print("\nLista invertida: " + str(arr))
print("\nVisualização apenas dos elementos de Lista em ordem invertida: ", end = "")

for element in arr:
  print(element, end=" ")

"""# Less Than"""

arr = [int(i) for i in input("Digite os números separados por vírgula: ").split(",")]
k = int(input("\nDigite o valor do parâmetro k (natural): "))
ans = []

for i in range(0, len(arr)):
  if arr[i] < k:
    ans.append(arr[i])

print("\nElementos de Lista menores do que k: ", end = "")

for element in ans:
  print(element, end = " ")

"""# Separate Even Odd"""

arr = [int(x) for x in input("Digite os números separados por vírgula: ").split(",")]
even = []
odd = []

for i in range(0, len(arr)):
  if(arr[i] % 2 == 0):
    even.append(arr[i])
  else:
    odd.append(arr[i])

print("\nLista: " + str(arr))
print("\nLista com seus valores pares: " + str(even))
print("\nLista com seus valores ímpares: " + str(odd))

"""# Count Distinct"""

arr = [4, 4, 5, 4, 3, 8, 4, 2, 4, 8, 1, 7]
dist_elem = set(arr)

print(len(dist_elem))
