# -*- coding: utf-8 -*-
"""Hackerrank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajGHWHeMKSV_m900qE3nzu6bdwSYYpEh

## ***Practice Python***

**Print Function**

Sem usar qualquer método de string, tente imprimir a sequência 123...n sem espaços, onde no dado de entrada, a primeira e única linha contém o inteiro n, 1<=n<=150, que corresponde ao tamanho da sequência unida de valores inteiros, positivos e consecutivos.
"""

if __name__ == '__main__':
  n = int(input())
  if 1<=n<=150:
    for i in range(1, n+1):
      print(i, end='')

"""**Loops**

Imprima o quadrado de cada número i em linha separada. No dado de entrada, a primeira e única linha contém o inteiro n, 1<=n<=20. Imprima n linhas, em que uma corresponda a cada i^2.
"""

if __name__ == '__main__':
    n = int(input())
    if 1<=n<=20:
      i = 0
      while i < n:
        print(i**2)
        i += 1

"""**Python If-Else**

Dado um número inteiro,, execute as seguintes ações condicionais:

Se n é ímpar, imprima Weird
Se n é par e está inclúido no range de 2 à 5, imprima Not Weird
Se n é par e está inclúido no range de 6 à 20, imprima Weird
Se n é par e maior do que 20, imprima Not Weird
"""

if __name__ == '__main__':
    n = int(input().strip())
    if n % 2 == 1:
      print('weird')
    elif n % 2 == 0 and 2 <= n <= 5:
      print('not weird')
    elif n % 2 == 0 and 6 <= n <= 20:
      print('weird')
    else:
      print('not weird')

"""**Lists**

Considere uma lista. Podem ser executados os seguintes comandos:

insert(i,e): Inserir inteiro e na posição i.

print(var): Imprima a lista.

remove(e): Exclua a primeira ocorrência do inteiro e.

append(e): Inserir inteiro e no final da lista.

sort: Classifique a lista.

pop: Pop o último elemento da lista.

reverse: Inverta a lista.

Inicialize sua lista e leia o valor de n seguido por n linhas de comandos onde cada comando será um dos 7 tipos listados acima. Iteraja cada comando em ordem e execute a operação correspondente em sua lista. A primeira linha contém o inteiro n denotando o número de comandos. Cada linha i das linhas subsequêntes n contém um dos comandos descritos acima.
"""

if __name__ == '__main__':

  list = []

  for i in range(int(input())):
    N = input().split()
    for i in range(1,len(N)):
      N[i] = int(N[i])

    if N[0] == "append":
      list.append(N[1])
    elif N[0] == "extend":
      list.extend(N[1:])
    elif N[0] == "insert":
      list.insert(N[1],N[2])
    elif N[0] == "remove":
      list.remove(N[1])
    elif N[0] == "pop":
      list.pop()
    elif N[0] == "index":
      list.index(N[1])
    elif N[0] == "count":
      list.count(N[1])
    elif N[0] == "sort":
      list.sort()
    elif N[0] == "reverse":
      list.reverse()
    else:
      N[0] == "print"
      print(list)

"""**List Comprehensions**

 Você recebe três inteiros  e representando as dimensões de um paralelepípedo junto com um inteiro . Imprima uma lista de todas as coordenadas possíveis fornecidas por zn(i,j,k) em uma grade 3D onde a soma de i+j+k não é igual à n. Aqui n 0<=i<=x; 0<=j<=y; 0<=k<=z. Por favor, use compreensões de lista em vez de vários loops
"""

x, y, z, n = [int(input()) for _ in range(4)]
print([[i, j, k] for i in range(x + 1) for j in range(y + 1) for k in range(z + 1) if i + j + k != n])