# -*- coding: utf-8 -*-
"""Producer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zS_KR5j2MWlGMwO-efZ3LvG2zMYW1r-
"""

!pip install confluent_kafka

import sys
import os

from confluent_kafka import Producer

def delivery_callback(err, msg):
    if err:
        print('%% Message failed delivery: %s\n', err)
    else:
        print('%% Message delivered to %s [%d]\n',
                          (msg.topic(), msg.partition()))

def createTopic():
    print("init");
    #topic = '25fi2ymi-topic1'
    topic = '25fi2ymi-default'

    # Consumer configuration
    # See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
    conf = {
        'bootstrap.servers': 'tricycle-01.srvs.cloudkafka.com:9094,tricycle-02.srvs.cloudkafka.com:9094,tricycle-03.srvs.cloudkafka.com:9094',
        'session.timeout.ms': 6000,
        'default.topic.config': {'auto.offset.reset': 'smallest'},
        'security.protocol': 'SASL_SSL',
	'sasl.mechanisms': 'SCRAM-SHA-256',
        'sasl.username': '25fi2ymi',
        'sasl.password': 'owaqWZ8jve0rsct5yHS3l9xGGK1rIL82'
    }

    p = Producer(conf)

    try:
        p.produce(topic, "my message new 2", callback=delivery_callback)
    except BufferError as e:
        print('%% Local producer queue is full (%d messages awaiting delivery): try again\n',
                          len(p))
    p.poll(0)

    print('%% Waiting for %d deliveries\n' % len(p))
    p.flush()

createTopic();