# -*- coding: utf-8 -*-
"""limpeza (DIO - ETL).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEN90-dg3c5nUJ23vYjNU8fuspUz1bIL
"""

import pandas as pd

df = df.read_csv("ocorrencia_2010_2020.csv",sep = ",",parse_dates = ['ocorrencia_dia'],dayfirst = True)
df.head()

df.loc[1,'ocorrencia_cidade'] # Busca pela posição de lable

df.loc[1:3] #Não confundir com índice de Array ou List

df.codigo_ocorrencia.is_unique

df.set_index('codigo_ocorrencia',inplace = True) # Índices passam a ser os valores desta coluna

df.reset_index(drop = True, inplace = True) # Retorna os índices originais

df.loc[0,'ocorrencia_aerodromo'] = '' # Limpeza dos dados: Remove as informações ou caracteres presente

df.loc[x] = y # y corresponde à informação a ser inserida na linha x

df.loc[:,'total_recomendacoes'] = x # Altera os dados de todas as linhas desta coluna para x

df['ocorrencia_uf_bkp'] = df.ocorrencia_uf # Criação de nova coluna com intenção de salvar dados de outra

df.loc[df.ocorrencia_uf == 'SP',['ocorrencia_classificacao']] = 'GRAVE'

df.loc[df.ocorrencia_aerodromo == '****',['ocorrencia_aerodromo']] = pd.NA # Limpeza dos dados: Substitui "*" por NA

df.replace(['**','###!','####','****','*****','NULL'],pd.NA,inplace = True) # Limpeza dos dados: Método dinâmico

df.isna() # Mostra onde é verdadeira a presença de dado NA. "isnull" também aplicável

df.isna().sum # Mostra a soma de dados NA. # "isnull" também aplicável

df.fillna(x,inplace = True) # Coloca x em todos os dados NA

df.fillna(value = {'total_recomendacoes': x},inplace = True) # Coloca nesta coluna o dado x no lugar de NA

df.drop(['total_recomendacoes_bkp'],axis = 1,inplace = True) # Apaga a coluna. Necessário sinalizar que será o eixo de coluna "axis"

df.dropna() # Exclui todos os dados NA

df.dropna(subset = ['x']) # Exclui toda a linha da coluna x se tiver dados NA

df.drop_duplicates() # Exclui linhas duplicadas