# -*- coding: utf-8 -*-
"""Dataframe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_mbLeU-sby-jrUGr_42StzpI16YTttJ9
"""

import pandas as pd

def createDataframe():

  map = {
      "name" : ["Huguinho", "Student 1", "Student 2"],
      "age" : [ 28, 18, 32 ],
      "location" : ["Santos", "São Paulo", "Rio de Janeiro"]
  }

  df = pd.DataFrame( map );

  print( df );

createDataframe()

def iterateDataframe():

  map = {
      "name" : ["Huguinho", "Student 1", "Student 2"],
      "age" : [ 28, 18, 32 ],
      "location" : ["Santos", "São Paulo", "Rio de Janeiro"]
  }

  df = pd.DataFrame( map );

  # não indicado para alto volume de dados ( somente para conhecimento )
  for index in df.index:
    print("item", df["name"][ index ], " | index", index  );

iterateDataframe()

def addColumnDataframe():

  map = {
      "name" : ["Huguinho", "Student 1", "Student 2"],
      "age" : [ 28, 18, 32 ],
      "location" : ["Santos", "São Paulo", "Rio de Janeiro"]
  }

  df = pd.DataFrame( map );

  # adicionando uma nova coluna
  address = ['Rua de teste 1', 'Rua de teste 2', 'Rua de teste 3'];

  df['address'] = address;

  print( df )

addColumnDataframe()

def removeColumnDataframe():

  map = {
      "name" : ["Huguinho", "Student 1", "Student 2"],
      "age" : [ 28, 18, 32 ],
      "location" : ["Santos", "São Paulo", "Rio de Janeiro"]
  }

  df = pd.DataFrame( map );

  # Removendo a linha pelo índice
  df = df.drop(1)

  print( df )

  print("---------------------------")

  # Removendo a coluna
  df = df.drop( columns=["age"] );

  print ( df );

removeColumnDataframe()

def filterDataframe():

  map = {
      "name" : ["Huguinho", "Student 1", "Student 2", "Student 3", "Student 4"],
      "age" : [ 28, 18, 32, 17, 14 ],
      "location" : ["Santos", "São Paulo", "Rio de Janeiro", "São Paulo", "São Paulo"]
  }

  df = pd.DataFrame( map );

  # criando o filtro
  filter = df["age"] >= 18;

  # Filtrando a lista
  filteredList = df[ filter ];

  print ( df );
  print("----------------------");
  print( filteredList )

filterDataframe()

def stringDataframe():

  map = {
      "name" : ["Huguinho", "Student 1", "Student 2", "Student 3", "Student 4"],
      "age" : [ 28, 18, 32, 17, 14 ],
      "location" : ["santos", "são Paulo", "rio de Janeiro", "são Paulo", "São Paulo"]
  }

  df = pd.DataFrame( map );


  print("original dataframe")
  print ( df );
  print("-------------------------------------------");

  # maiúscula
  print()
  print("Upper case")
  print( df["location"].str.upper() )
  print("--------------------------------------------");

  print()
  print("Upper in dataframe")
  df["location"] = df["location"].str.upper()
  print( df );
  print("------------------------------------------");

  # Somente a primeira maiuscula
  print()
  print("Capitalize")
  df["location"] = df["location"].str.capitalize()
  print( df );
  print("------------------------------------------");

  # Somente a primeira de cada palavra
  print()
  print("Title")
  df["location"] = df["location"].str.title()
  print( df );
  print("------------------------------------------");

stringDataframe()

def renameDataframe():

  map = {
      "name" : ["Huguinho", "Student 1", "Student 2", "Student 3", "Student 4"],
      "age" : [ 28, 18, 32, 17, 14 ],
      "location" : ["Santos", "São Paulo", "Rio de Janeiro", "São Paulo", "São Paulo"]
  }

  df = pd.DataFrame( map );

  # renomeando
  df = df.rename(columns={"age": "idade", "location": "localizacao"})

  print ( df );
  print("----------------------");

renameDataframe()

def jsonDataframe():

  map = {
      "name" : ["Huguinho", "Student 1", "Student 2", "Student 3", "Student 4"],
      "age" : [ 28, 18, 32, 17, 14 ]
  }

  df = pd.DataFrame( map );

  # json
  json = df.to_json(orient="records")

  print ( df );
  print("----------------------");
  print( json )

jsonDataframe()

def readCsv():
  url = "https://raw.githubusercontent.com/huguinho-alves/python_aceleracao_everys/main/arquivo.csv"
  df = pd.read_csv( url )

  print( df )

readCsv()

