# -*- coding: utf-8 -*-
"""Projeto Python-Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Km1XCergKDuNmuG3jJidsJJWa9KxbkWI
"""

import pandas as pd # Importação para acesso às ferramentas da biblioteca Pandas

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Curso_Python_Pandas_Digital_Innovation-master/datasets/Gapminder.csv",error_bad_lines=False, sep=";")
# Carregamento do arquivo base para o dataframe

df.head() # Mostra as 5 primeiras linhas do dataframe criado a partir do arquivo

df = df.rename(columns={"country":"Pais", "continent": "continente", "year":"Ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gdpPercap": "PIB"})
# Renomeação das colunas da tabela (dataframe)

df.dtypes # mostra os tipos de dados de cada coluna

df.describe() # mostra dados estatísticos das colunas

df["continente"].unique() # Mostra os dados presentes na coluna "continente"

df.groupby("continente")["Pais"].nunique() # Mostra a quantidade de "Pais" presente em "continente"

df.groupby("Ano")["Expectativa de vida"].mean() # Mostra o valor médio dos dados em "Expectativa de Vida" por "Ano"

df["PIB"].mean() # Mostra o valor médio dos dados em "PIB"

df["PIB"].sum() # Mostra a soma dos dados em "PIB"

import pandas as pd

df1 = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Curso_Python_Pandas_Digital_Innovation-master/datasets/Aracaju.xlsx")
df2 = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Curso_Python_Pandas_Digital_Innovation-master/datasets/Fortaleza.xlsx")
df3 = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Curso_Python_Pandas_Digital_Innovation-master/datasets/Natal.xlsx")
df4 = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Curso_Python_Pandas_Digital_Innovation-master/datasets/Recife.xlsx")
df5 = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Curso_Python_Pandas_Digital_Innovation-master/datasets/Salvador.xlsx")
# Leitura dos arquivos

df = pd.concat([df1,df2,df3,df4,df5]) # Juntando todos os arquivos

df.dtypes

df["LojaID"] = df["LojaID"].astype("object") # Alterando o tipo de dado da coluna LojaID

df.dtypes

df.isnull().sum() # Consultando linhas com valores faltantes

df["Vendas"].fillna(df["Vendas"].mean(), inplace=True) # Substituindo os valores nulos pela média

df["Vendas"].mean()

df.isnull().sum()

df["Vendas"].fillna(0, inplace=True) # Substituindo os valores nulos por zero

df.dropna(inplace=True) # Apagando as linhas com valores nulos

df.dropna(subset=["Vendas"], inplace=True) # Apagando as linhas com valores nulos com base apenas na colun "Vendas"

df.dropna(how="all", inplace=True) # Removendo linhas que estejam com valores faltantes em todas as colunas

df["Receita"] = df["Vendas"].mul(df["Qtde"]) # Criando a coluna de receita

df["Receita/Vendas"] = df["Receita"] / df["Vendas"] # Criação da coluna Receita por Venda

df["Receita"].max() # Retornando a maior receita

df["Receita"].min() # Retornando a menor receita

df.nlargest(3, "Receita") # Mostra as 3 maiores Receitas em ordem decrescente

df.nsmallest(3, "Receita") # Mostra as 3 menores Receitas em ordem decrescente

df.groupby("Cidade")["Receita"].sum() # Soma dos dados de "Receita" por cidade

df.sort_values("Receita", ascending=False).head(10) # Ordenando o conjunto de dados por "Receita" em ordem decrescente

df["Data"] = df["Data"].astype("int64") # Transforma a coluna de data em tipo inteiro

df.dtypes

df["Data"] = pd.to_datetime(df["Data"]) # Transforma a coluna de data em formato de data

df.groupby(df["Data"].dt.year)["Receita"].sum() # Agrupamento por ano

df["Ano_Venda"] = df["Data"].dt.year # Criando uma nova coluna com o ano

df["mes_venda"], df["dia_venda"] = (df["Data"].dt.month, df["Data"].dt.day) # Extraindo o mês e o dia

df["Data"].min() # Retornando a data mais antiga

df["diferenca_dias"] = df["Data"] - df["Data"].min() # Calculando a diferença de dias

df["trimestre_venda"] = df["Data"].dt.quarter # Criando a coluna de trimestre

vendas_marco_19 = df.loc[(df["Data"].dt.year == 2019) & (df["Data"].dt.month == 3)]
# Filtrando as vendas de 2019 do mês de março

df["LojaID"].value_counts(ascending=False) # Mostra a quantidade de ítens vendidos por "LojaID" em ordem decrescente

df["LojaID"].value_counts(ascending=False).plot.bar() # Gráfico de barras

df["LojaID"].value_counts().plot.barh() # Gráfico de barras horizontais

df["LojaID"].value_counts(ascending=True).plot.barh(); # Gráfico de barras horizontais sem o título técnico acima devido à ";"

df.groupby(df["Data"].dt.year)["Receita"].sum().plot.pie() # Gráfico de Pizza

df["Cidade"].value_counts() # Total vendas por cidade

import matplotlib.pyplot as plt
df["Cidade"].value_counts().plot.bar(title="Total vendas por Cidade")
plt.xlabel("Cidade")
plt.ylabel("Total Vendas");
# Adicionando um título e alterando o nome dos eixos

df["Cidade"].value_counts().plot.bar(title="Total vendas por Cidade", color="red")
plt.xlabel("Cidade")
plt.ylabel("Total Vendas");
# Alterando a cor

plt.style.use("ggplot") # Alterando o estilo

df.groupby(df["mes_venda"])["Qtde"].sum().plot(title = "Total Produtos vendidos x mês")
plt.xlabel("Mês")
plt.ylabel("Total Produtos Vendidos")
plt.legend();

df.groupby(df["mes_venda"])["Qtde"].sum()

df_2019 = df[df["Ano_Venda"] == 2019] # Selecionando apenas as vendas de 2019

df_2019.groupby(df_2019["mes_venda"])["Qtde"].sum()

df_2019.groupby(df_2019["mes_venda"])["Qtde"].sum().plot(marker = "o")
plt.xlabel("Mês")
plt.ylabel("Total Produtos Vendidos")
plt.legend();
# Total produtos vendidos por mês com marcador de ponto

plt.hist(df["Qtde"], color="orangered"); # Histograma

plt.scatter(x=df_2019["dia_venda"], y = df_2019["Receita"]);

df_2019.groupby(df_2019["mes_venda"])["Qtde"].sum().plot(marker = "v")
plt.title("Quantidade de produtos vendidos x mês")
plt.xlabel("Mês")
plt.ylabel("Total Produtos Vendidos");
plt.legend()
plt.savefig("grafico QTDE x MES.png")
# Salvando em png

import matplotlib.pyplot as plt
plt.style.use("seaborn")
# Importando as bibliotecas de plotagem

df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Curso_Python_Pandas_Digital_Innovation-master/datasets/AdventureWorks.xlsx")

df.dtypes

df["Valor Venda"].sum() # Qual a Receita total?

df["custo"] = df["Custo Unitário"].mul(df["Quantidade"]) # Criando a coluna de custo. Qual o custo Total?

round(df["custo"].sum(), 2) # Qual o custo Total? (aproximação)

df["lucro"]  = df["Valor Venda"] - df["custo"] # Agora que temos a receita e custo e o total, podemos achar o Lucro total
# Vamos criar uma coluna de Lucro que será Receita - Custo

round(df["lucro"].sum(),2) # Total Lucro

df["Tempo_envio"] = df["Data Envio"] - df["Data Venda"] # Criando uma coluna com total de dias para enviar o produto

df["Tempo_envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days # Extraindo apenas os dias

df["Tempo_envio"].dtype # Verificando o tipo da coluna Tempo_envio

df.groupby("Marca")["Tempo_envio"].mean() # Média do tempo de envio por Marca

df.isnull().sum()

df.groupby([df["Data Venda"].dt.year, "Marca"])["lucro"].sum() # Agrupamento por ano e marca

pd.options.display.float_format = '{:20,.2f}'.format # Aproximação dos valores em 2 casas decimais

lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["lucro"].sum().reset_index()
lucro_ano
# Resetando o index

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False) # Qual o total de produtos vendidos?

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");
# Gráfico Total de produtos vendidos

df.groupby(df["Data Venda"].dt.year)["lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df.groupby(df["Data Venda"].dt.year)["lucro"].sum()

df_2009 = df[df["Data Venda"].dt.year == 2009] # Selecionando apenas as vendas de 2009

df_2009.groupby(df_2009["Data Venda"].dt.month)["lucro"].sum().plot(title="Lucro x Mês")
plt.xlabel("Mês")
plt.ylabel("Lucro");

df_2009.groupby("Marca")["lucro"].sum().plot.bar(title="Lucro x Marca")
plt.xlabel("Marca")
plt.ylabel("Lucro")
plt.xticks(rotation='horizontal');

df_2009.groupby("Classe")["lucro"].sum().plot.bar(title="Lucro x Classe")
plt.xlabel("Classe")
plt.ylabel("Lucro")
plt.xticks(rotation='horizontal');

df["Tempo_envio"].describe()

plt.boxplot(df["Tempo_envio"]); # Gráfico de Boxplot

plt.hist(df["Tempo_envio"]); # Histograma

df["Tempo_envio"].min() # Tempo mínimo de envio

df['Tempo_envio'].max() # Tempo máximo de envio

df[df["Tempo_envio"] == 20] # Identificando o Outlier

df.to_csv("df_vendas_novo.csv", index=False)