# -*- coding: utf-8 -*-
"""projeto (DIO - ETL).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8gYK4Ho3Pha-5qPHZmqGTbmVhSGM1i2
"""

import pandas as pd # Recomendado que os arquivos com dados para extração estejam no mesmo diretório deste projeto
import pandera as pa # "pandera" evitará inconsistências nas datas, que podem ocorrer mesmo com uso de "parse_dates"
# Caso "pandera" não esteja disponível, executar "pip install pandera"

df = df.read_csv("ocorrencia_2010_2020.csv",sep = ",",parse_dates = ['ocorrencia_dia'],dayfirst = True) # Arquivo csv acima é exemplo para extração de dados
df.head() # Imprime as 5 primeiras linhas de df. Pode ser parametrizado
df.tail() # Imprime as 5 útimas linhas de df. Pode ser parametrizado

schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String),
        "ocorrencia_uf": pa.Column(pa.String,pa.Check.str_length(2,2)),
        "ocorrencia_aerodromo": pa.Column(pa.String),
        "ocorrencia_dia": pa.Column(pa.Datetime),
        "ocorrencia_hora": pa.Column(pa.String,pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'),nullable = True)
        "total_recomendacoes": pa.Column(pa.Int)

    }
)

schema.validate(df)

df.dtypes # Verifica os tipos de dados presentes

df.ocorrencia_dia.dt.month # "ocorrencia_dia" precisa estar no formato e conteúdo correto de data (datetime) para o Python (uso de "parse_dates")