# -*- coding: utf-8 -*-
"""transformação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ueAZm9OX7BP37qQlDHfMfGT04s5Aapw
"""

import pandas as pd
import pandera as pa

valores_ausentes = ['**','###!','####','****','*****','NULL']
df = df.read_csv("ocorrencia_2010_2020.csv",sep = ",",parse_dates = ['ocorrencia_dia'],dayfirst = True,na_values = valores_ausentes)
df.head()

schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String),
        "ocorrencia_uf": pa.Column(pa.String,pa.Check.str_length(2,2),nullable = True),
        "ocorrencia_aerodromo": pa.Column(pa.String,nullable = True),
        "ocorrencia_dia": pa.Column(pa.Datetime),
        "ocorrencia_hora": pa.Column(pa.String,pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'),nullable = True)
        "total_recomendacoes": pa.Column(pa.Int)

    }
)

schema.validate(df)

df.iloc[x] # Busca pela posição do índice x

filtro = df.ocorrencia_uf.isnull() # Criação do filtro para facilitar a localização dos dados nulos
df.loc[filtro]

# Ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro,'ocorrencia_cidade']

# Ocorrências cuja classificação == INCIDENTE GRAVE e o estado == SP
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

# Ocorrências cuja (classificação == INCIDENTE GRAVE ou classificação == INCIDENTE) e o estado == SP
filtro1 = (df.ocorrencia_classificacao == 'INCIDENTE GRAVE') | (df.ocorrencia_classificacao == 'INCIDENTE')
# Outra opção Linha 2 -> filtro1 = (df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE','INCIDENTE'])
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

# Ocorrências cuja cidade comecem com a letra C
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

# Ocorrências cuja cidade terminem com a letra A
filtro = df.ocorrencia_cidade.str[-1] == 'A'
df.loc[filtro]

# Ocorrências cuja cidade contém os caracteres MA
filtro = df.ocorrencia_cidade.str.contains('MA') # Aceitável operadores. Ex.: ('MA | AL')
df.loc[filtro]

# Ocorrências do ano de 2015
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

# Ocorrências do ano de 2015 e Mẽs 12
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
# Outra opção Linhas 2 e 3 -> filtro = (df.ocorrencia_dia.dt.year == 2015) & (df.ocorrencia_dia.dt.month == 12)
# Se Linha 4 é aplicada, deve-se utilizar "filtro"
df.loc[filtro1 & filtro2]

df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora)

filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 13:00:00'
df.loc[filtro1 & filtro2]

# Ocorrências do ano de 2015 e mês 03
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 3
df201503 = df.loc[filtro1 & filtro2]
df201503

df.count()

df201503.groupby(['codigo_ocorrencia']).codigo_ocorrencia.count()
df201503.groupby(['codigo_ocorrencia']).size() # Em lugar da Linha 1, evita-se problemas com contagem de nulos

df201503.groupby(['codigo_ocorrencia']).size().sort_values()

df201503.groupby(['codigo_ocorrencia']).size().sort_values(ascending = False)

filtro1 = df.ocorrencia_dia.dt.year == 2010
filtro2 = df.ocorrencia_uf.isin(['SP','MG','ES','RJ'])
dfsudeste2010 = df.loc[filtro1 & filtro2]
dfsudeste2010

dfsudeste2010.groupby(['ocorrencia_classificacao']).size()

dfsudeste2010.groupby(['ocorrencia_aerodromo'],dropna = False).total_recomendacoes.sum() # "dropna" contabiliza dados NA

filtro = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade',dfsudeste2010.ocorrencia_dia.dt.month]).total_recomendacoes.sum()