# -*- coding: utf-8 -*-
"""Funções (Aceleração Everis).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFi8P8I_7jS8s7eeDweowtKcHwP6y9D4
"""

def forWithMap():

  person1 = {
      'name' : 'Huguinho',
      'title' : 'Expert IT Techonology'
  };

  person2 = {
      'name' : 'User 2',
      'title' : 'Student from everis Aceleration'
  };

  lista = [];
  lista.append( person1 );
  lista.append( person2 );

  print('tamanho do array', len( lista ) );

  for obj in lista:
    print('Nome: ', obj['name'], ' | title: ', obj['title'] );

forWithMap();