# -*- coding: utf-8 -*-
"""GeeksForGeeks DIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUmqgW6Ma62VKNxaGAJIsbXKoKwk_ntd
"""

numbers = []
strings = []
names = ["John", "Eric", "Jessica"]

numbers.append(1)
numbers.append(2)
numbers.append(3)

strings.append("hello")
strings.append("world")

second_name = names[1]

print(numbers)
print(strings)
print(f"The second name on the names list is %s" % second_name)

sentence = "the quick brown fox jumps over the lazy dog"
words = sentence.split()
word_lengths = []
for word in words:
      #if word != "the":
          word_lengths.append(len(word))
print(words)
print(word_lengths)

phonebook = {}
phonebook["John"] = 938477566
phonebook["Jack"] = 938377264
phonebook["Jill"] = 947662781
print(phonebook)

data = ("John", "Doe", 53.44)
format_string = "Hello %s %s. Your current balance is $%s."

print(format_string % data)
print(type(53.44))

astring = "Hello world!"
astring2 = 'Hello world!'

print(len(astring))
print(astring.index("o"))
print(astring.count("l"))
print(astring[3:7])
print(astring[3:7:2])
print(astring[3:7:1])
print(astring[::-1])
print(astring.upper())
print(astring.lower())
print(astring.startswith("Hello"))
print(astring.endswith("asdfasdfasdf"))

afewwords = astring.split(" ")

s = "Strings are awesome!"

print("Length of s = %d" % len(s))
print("The first occurrence of the letter a = %d" % s.index("a"))
print("a occurs %d times" % s.count("a"))
print("The first five characters are '%s'" % s[:5])
print("The next five characters are '%s'" % s[5:10])
print("The thirteenth character is '%s'" % s[12])
print("The characters with odd index are '%s'" %s[1::2])
print("The last five characters are '%s'" % s[-5:])
print("String in uppercase: %s" % s.upper())
print("String in lowercase: %s" % s.lower())

if s.startswith("Str"):
    print("String starts with 'Str'. Good!")
if s.endswith("ome!"):
    print("String ends with 'ome!'. Good!")

print("Split the words of the string: %s" % s.split(" "))

number = 16
second_number = 0
first_array = [1,2,3]
second_array = [1,2]

if number > 15:
    print("1")

if first_array:
    print("2")

if len(second_array) == 2:
    print("3")

if len(first_array) + len(second_array) == 5:
    print("4")

if first_array and first_array[0] == 1:
    print("5")

if not second_number:
    print("6")

if second_array not in first_array:
    print("7")

if first_array is not second_array:
    print("8")

name = "John"
if name in ["John", "Rick"]:
    print("Your name is either John or Rick.")

x = [1,2,3]
y = [1,2,3]
print(x == y) # Prints out True
print(x is y) # Prints out False

print(not False) # Prints out True
print((not False) == (False)) # Prints out False

remainder = 11 % 3
print(remainder)

helloworld = "hello" + " " + "world"
print(helloworld)

lotsofhellos = "hello" * 10
print(lotsofhellos)

def my_function():
    print("Hello From My Function!")

def my_function_with_args(username, greeting):
    print("Hello, %s, From My Function!, I wish you %s"%(username, greeting))

def sum_two_numbers(a, b):
    return a + b

my_function()
my_function_with_args("John Doe", "a great year!")

sum_two_numbers(1,2)

def list_benefits():
    return "More organized code", "More readable code", "Easier code reuse", "Allowing programmers to share and connect code together"

def build_sentence(benefit):
    return "%s is a benefit of functions!" % benefit

def name_the_benefits_of_functions():
    list_of_benefits = list_benefits()
    for benefit in list_of_benefits:
        print(build_sentence(benefit))

name_the_benefits_of_functions()

numbers = [34.6, -203.4, 44.9, 68.3, -12.2, 44.6, 12.7]
newlist = []

for x in numbers:
    if x > 0:
        newlist.append(int(x))
print(newlist)

def forWithMap():

  person1 = {
      'name' : 'Huguinho',
      'title' : 'Expert IT Techonology'
  };

  person2 = {
      'name' : 'User 2',
      'title' : 'Student from everis Aceleration'
  };

  lista = [];
  lista.append( person1 );
  lista.append( person2 );

  print('tamanho do array', len( lista ) );

  for obj in lista:
    print('Nome: ', obj['name'], ' | title: ', obj['title'] );

forWithMap();

class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()
print(myobjectx.variable)
print(myobjectx.function())

import re

find_functions = []

for function in dir(re):
    if "find" in function:
        find_functions.append(function)

sorted(find_functions)
print(find_functions)

# fill in this function
def fib():
    a, b = 1, 1
    while 1:
        yield a
        a, b = b, a + b
# testing code
import types
if type(fib()) == types.GeneratorType:
    print("Good, The fib function is a generator.")

    counter = 0
    for n in fib():
        print(n)
        counter += 1
        if counter == 10:
            break